### ISSUE TITLE
Include value of experimental conditions (e.g. stimulus) in the training and posterior sampling for MNLE.

### ISSUE THREAD

**Issue by alexgarciaduran** [mackelab/mnle-for-ddms#2]
Greetings,

Firstly, I would like to express my appreciation for this powerful tool.
Currently, I am trying to fit a model (DDM) with three experimental conditions (e.g. stimulus) and 16 parameters. My problem is that I do not know how to sample from the posterior distributions considering these conditions. For the training, I just include them as additional inputs to the network, as suggested in the paper.
Then, should I consider them as observed data (and also as inputs for the training)?

Thanks in advance,
Alex

**Comment by janfb** [comment]
Hi @alexgarciaduran 
as mentioned in my email, there is a corresponding open issue in the SBI toolbox> https://github.com/mackelab/sbi/issues/717 
I will work on fixing this soon!

**Comment by alexgarciaduran** [comment]
Thanks a lot!
